### ISSUE TITLE
newer Optix versions?

### ISSUE THREAD

**Issue by dkokron** [ingowald/RTOW-OptiX#5]
Many thanks for publishing this code and the corresponding blog posts.  Has anyone tested this repository with newer Optix releases (6.5 an/or 7.0)?

Dan

**Comment by ingowald** [comment]
This should still run in Optix 6.5; however, Optix 7 has a completely different (and much lower-level) API that this will no longer compile with. 

I am in fact currently working on a "convenience" library that adds a slightly higher abstraction library on top of Optix 7 that makes 7 look a bit more like 6 ... and with that library I do already have a test case that pretty much implements this same example. 

That said, said library isn't ready for public consumption yet - it does have enough things working to reproduce this RTOW example, but there's tons of things that are still missing, and I don't want to share this unless it's become a bit more mature. I'll post here when I do, though!

**Comment by ingowald** [comment]
If interested in a OptiX 7 based version of Pete's RTOW "final chapter" scene, have a look at https://owl-project.github.io/, and in particular, the "ng/sample05-rtow". 
OWL implements an abstraction layer similar to the Optix 6 node graph that was used in this example, and therefore produces a final RTOW sample that looks very similar to this one - but internally, builds on top of Optix 7.
